// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportHub.Api.Data;

#nullable disable

namespace SportHub.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260710195722_AddPayments")]
    partial class AddPayments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SportHub.Api.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("int");

                    b.Property<bool>("HiddenFromCustomer")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("PayOnSite");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("NotRequired");

                    b.Property<DateTime?>("PickupDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RentalStatus")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SportHub.Api.Models.BookingEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("BookingEquipment");
                });

            modelBuilder.Entity("SportHub.Api.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DailyRentalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PackageHourlyPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DailyRentalPrice = 30m,
                            ImageUrl = "/uploads/seed/football/football-ball.png",
                            Name = "Football",
                            PackageHourlyPrice = 10m,
                            Quantity = 30,
                            SportId = 1
                        },
                        new
                        {
                            Id = 2,
                            DailyRentalPrice = 50m,
                            ImageUrl = "/uploads/seed/tennis/tennis-racket.png",
                            Name = "Tennis Racket",
                            PackageHourlyPrice = 15m,
                            Quantity = 12,
                            SportId = 2
                        },
                        new
                        {
                            Id = 3,
                            DailyRentalPrice = 70m,
                            ImageUrl = "/uploads/seed/padel/padel-racket.png",
                            Name = "Padel Racket",
                            PackageHourlyPrice = 20m,
                            Quantity = 10,
                            SportId = 3
                        },
                        new
                        {
                            Id = 4,
                            DailyRentalPrice = 35m,
                            ImageUrl = "/uploads/seed/basketball/basketball-ball.png",
                            Name = "Basketball",
                            PackageHourlyPrice = 10m,
                            Quantity = 25,
                            SportId = 4
                        },
                        new
                        {
                            Id = 5,
                            DailyRentalPrice = 20m,
                            ImageUrl = "/uploads/seed/football/training-cones.png",
                            Name = "Football Training Cones",
                            PackageHourlyPrice = 5m,
                            Quantity = 60,
                            SportId = 1
                        },
                        new
                        {
                            Id = 6,
                            DailyRentalPrice = 25m,
                            ImageUrl = "/uploads/seed/football/training-hurdles.png",
                            Name = "Football Training Hurdles",
                            PackageHourlyPrice = 8m,
                            Quantity = 24,
                            SportId = 1
                        },
                        new
                        {
                            Id = 7,
                            DailyRentalPrice = 25m,
                            ImageUrl = "/uploads/seed/football/agility-ladder.png",
                            Name = "Football Agility Ladder",
                            PackageHourlyPrice = 8m,
                            Quantity = 15,
                            SportId = 1
                        },
                        new
                        {
                            Id = 8,
                            DailyRentalPrice = 15m,
                            ImageUrl = "/uploads/seed/football/away-vest.png",
                            Name = "Away Vest",
                            PackageHourlyPrice = 5m,
                            Quantity = 40,
                            SportId = 1
                        },
                        new
                        {
                            Id = 9,
                            DailyRentalPrice = 20m,
                            ImageUrl = "/uploads/seed/tennis/tennis-ball.png",
                            Name = "Tennis Ball",
                            PackageHourlyPrice = 5m,
                            Quantity = 80,
                            SportId = 2
                        },
                        new
                        {
                            Id = 10,
                            DailyRentalPrice = 120m,
                            ImageUrl = "/uploads/seed/tennis/tennis-ball-machine.png",
                            Name = "Tennis Ball Machine",
                            PackageHourlyPrice = 45m,
                            Quantity = 4,
                            SportId = 2
                        },
                        new
                        {
                            Id = 11,
                            DailyRentalPrice = 35m,
                            ImageUrl = "/uploads/seed/tennis/ball-cart.png",
                            Name = "Tennis Ball Cart",
                            PackageHourlyPrice = 10m,
                            Quantity = 8,
                            SportId = 2
                        },
                        new
                        {
                            Id = 12,
                            DailyRentalPrice = 25m,
                            ImageUrl = "/uploads/seed/tennis/scoreboard.png",
                            Name = "Tennis Scoreboard",
                            PackageHourlyPrice = 8m,
                            Quantity = 6,
                            SportId = 2
                        },
                        new
                        {
                            Id = 13,
                            DailyRentalPrice = 25m,
                            ImageUrl = "/uploads/seed/padel/padel-ball.png",
                            Name = "Padel Ball",
                            PackageHourlyPrice = 8m,
                            Quantity = 60,
                            SportId = 3
                        },
                        new
                        {
                            Id = 14,
                            DailyRentalPrice = 35m,
                            ImageUrl = "/uploads/seed/padel/ball-basket-cart.png",
                            Name = "Padel Ball Basket Cart",
                            PackageHourlyPrice = 10m,
                            Quantity = 8,
                            SportId = 3
                        },
                        new
                        {
                            Id = 15,
                            DailyRentalPrice = 25m,
                            ImageUrl = "/uploads/seed/padel/scoreboard.png",
                            Name = "Padel Scoreboard",
                            PackageHourlyPrice = 8m,
                            Quantity = 6,
                            SportId = 3
                        },
                        new
                        {
                            Id = 16,
                            DailyRentalPrice = 60m,
                            ImageUrl = "/uploads/seed/padel/target-rebounder-net.png",
                            Name = "Target Rebounder Net",
                            PackageHourlyPrice = 20m,
                            Quantity = 5,
                            SportId = 3
                        },
                        new
                        {
                            Id = 17,
                            DailyRentalPrice = 40m,
                            ImageUrl = "/uploads/seed/basketball/basketball-ball-rack.png",
                            Name = "Basketball Ball Rack",
                            PackageHourlyPrice = 12m,
                            Quantity = 5,
                            SportId = 4
                        },
                        new
                        {
                            Id = 18,
                            DailyRentalPrice = 20m,
                            ImageUrl = "/uploads/seed/basketball/training-cones.png",
                            Name = "Basketball Training Cones",
                            PackageHourlyPrice = 5m,
                            Quantity = 60,
                            SportId = 4
                        },
                        new
                        {
                            Id = 19,
                            DailyRentalPrice = 25m,
                            ImageUrl = "/uploads/seed/basketball/training-hurdles.png",
                            Name = "Basketball Training Hurdles",
                            PackageHourlyPrice = 8m,
                            Quantity = 24,
                            SportId = 4
                        },
                        new
                        {
                            Id = 20,
                            DailyRentalPrice = 25m,
                            ImageUrl = "/uploads/seed/basketball/agility-ladder.png",
                            Name = "Basketball Agility Ladder",
                            PackageHourlyPrice = 8m,
                            Quantity = 15,
                            SportId = 4
                        },
                        new
                        {
                            Id = 21,
                            DailyRentalPrice = 80m,
                            ImageUrl = "/uploads/seed/boxing/heavy-punching-bag.png",
                            Name = "Heavy Punching Bag",
                            PackageHourlyPrice = 25m,
                            Quantity = 8,
                            SportId = 5
                        },
                        new
                        {
                            Id = 22,
                            DailyRentalPrice = 60m,
                            ImageUrl = "/uploads/seed/boxing/double-end-punching-bag.png",
                            Name = "Double-end Punching Bag",
                            PackageHourlyPrice = 20m,
                            Quantity = 6,
                            SportId = 5
                        },
                        new
                        {
                            Id = 23,
                            DailyRentalPrice = 50m,
                            ImageUrl = "/uploads/seed/boxing/reflex-punching-ball.png",
                            Name = "Reflex Punching Ball",
                            PackageHourlyPrice = 18m,
                            Quantity = 6,
                            SportId = 5
                        },
                        new
                        {
                            Id = 24,
                            DailyRentalPrice = 45m,
                            ImageUrl = "/uploads/seed/boxing/speed-bag.png",
                            Name = "Speed Bag",
                            PackageHourlyPrice = 15m,
                            Quantity = 6,
                            SportId = 5
                        },
                        new
                        {
                            Id = 25,
                            DailyRentalPrice = 15m,
                            ImageUrl = "/uploads/seed/boxing/jump-rope.png",
                            Name = "Jump Rope",
                            PackageHourlyPrice = 5m,
                            Quantity = 25,
                            SportId = 5
                        },
                        new
                        {
                            Id = 26,
                            DailyRentalPrice = 30m,
                            ImageUrl = "/uploads/seed/boxing/medicine-ball.png",
                            Name = "Medicine Ball",
                            PackageHourlyPrice = 10m,
                            Quantity = 12,
                            SportId = 5
                        },
                        new
                        {
                            Id = 27,
                            DailyRentalPrice = 70m,
                            ImageUrl = "/uploads/seed/archery/bow-equipment.png",
                            Name = "Bow",
                            PackageHourlyPrice = 20m,
                            Quantity = 12,
                            SportId = 6
                        },
                        new
                        {
                            Id = 28,
                            DailyRentalPrice = 25m,
                            ImageUrl = "/uploads/seed/archery/arrows-equipment.png",
                            Name = "Arrows",
                            PackageHourlyPrice = 8m,
                            Quantity = 120,
                            SportId = 6
                        },
                        new
                        {
                            Id = 29,
                            DailyRentalPrice = 20m,
                            ImageUrl = "/uploads/seed/archery/arrow-holder-equipment.png",
                            Name = "Arrow Holder",
                            PackageHourlyPrice = 6m,
                            Quantity = 20,
                            SportId = 6
                        },
                        new
                        {
                            Id = 30,
                            DailyRentalPrice = 15m,
                            ImageUrl = "/uploads/seed/archery/arm-guard.png",
                            Name = "Arm Guard",
                            PackageHourlyPrice = 5m,
                            Quantity = 25,
                            SportId = 6
                        },
                        new
                        {
                            Id = 31,
                            DailyRentalPrice = 15m,
                            ImageUrl = "/uploads/seed/archery/finger-tab.png",
                            Name = "Finger Tab",
                            PackageHourlyPrice = 5m,
                            Quantity = 25,
                            SportId = 6
                        },
                        new
                        {
                            Id = 32,
                            DailyRentalPrice = 45m,
                            ImageUrl = "/uploads/seed/archery/archery-target-target-stand.png",
                            Name = "Archery Target Stand",
                            PackageHourlyPrice = 15m,
                            Quantity = 10,
                            SportId = 6
                        });
                });

            modelBuilder.Entity("SportHub.Api.Models.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsOutOfService")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/uploads/seed/football/5-a-side-football-field.png",
                            IsOutOfService = false,
                            Name = "5-a-side Football Field",
                            PricePerHour = 350m,
                            SportId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/uploads/seed/tennis/tennis-court-facility.png",
                            IsOutOfService = false,
                            Name = "Tennis Court 1",
                            PricePerHour = 250m,
                            SportId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/uploads/seed/padel/padel-court-facility.png",
                            IsOutOfService = false,
                            Name = "Padel Court 1",
                            PricePerHour = 400m,
                            SportId = 3
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/uploads/seed/basketball/indoor-basketball-court.png",
                            IsOutOfService = false,
                            Name = "Indoor Basketball Court",
                            PricePerHour = 300m,
                            SportId = 4
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/uploads/seed/football/7-a-side-football-field.png",
                            IsOutOfService = false,
                            Name = "7-a-side Football Field",
                            PricePerHour = 500m,
                            SportId = 1
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "/uploads/seed/football/11-a-side-full-football-field.png",
                            IsOutOfService = false,
                            Name = "11-a-side Full Football Field",
                            PricePerHour = 800m,
                            SportId = 1
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "/uploads/seed/basketball/outdoor-basketball-court.png",
                            IsOutOfService = false,
                            Name = "Outdoor Basketball Court",
                            PricePerHour = 220m,
                            SportId = 4
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "/uploads/seed/boxing/boxing-ring-facility.png",
                            IsOutOfService = false,
                            Name = "Boxing Ring",
                            PricePerHour = 280m,
                            SportId = 5
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "/uploads/seed/archery/archry-facility.png",
                            IsOutOfService = false,
                            Name = "Archery Range",
                            PricePerHour = 240m,
                            SportId = 6
                        });
                });

            modelBuilder.Entity("SportHub.Api.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("longtext");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderReference")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SportHub.Api.Models.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Football fields for 5-a-side, 7-a-side, and full matches with training equipment.",
                            ImageUrl = "/uploads/seed/football/sport-image.png",
                            Name = "Football"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tennis courts with rackets, balls, carts, and training equipment.",
                            ImageUrl = "/uploads/seed/tennis/sport-image.png",
                            Name = "Tennis"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Padel courts with rackets, balls, scoreboards, and training gear.",
                            ImageUrl = "/uploads/seed/padel/sport-image.png",
                            Name = "Padel"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Indoor and outdoor basketball courts with balls and training equipment.",
                            ImageUrl = "/uploads/seed/basketball/sport-image.png",
                            Name = "Basketball"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Boxing ring and training equipment for strength, speed, and reflex practice.",
                            ImageUrl = "/uploads/seed/boxing/sport-image.png",
                            Name = "Boxing"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Archery range with bows, arrows, safety gear, and target stands.",
                            ImageUrl = "/uploads/seed/archery/sport-image.png",
                            Name = "Archery"
                        });
                });

            modelBuilder.Entity("SportHub.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SportHub.Api.Models.Booking", b =>
                {
                    b.HasOne("SportHub.Api.Models.Facility", "Facility")
                        .WithMany("Bookings")
                        .HasForeignKey("FacilityId");

                    b.HasOne("SportHub.Api.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Api.Models.BookingEquipment", b =>
                {
                    b.HasOne("SportHub.Api.Models.Booking", "Booking")
                        .WithMany("BookingEquipment")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportHub.Api.Models.Equipment", "Equipment")
                        .WithMany("BookingEquipment")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("SportHub.Api.Models.Equipment", b =>
                {
                    b.HasOne("SportHub.Api.Models.Sport", "Sport")
                        .WithMany("Equipment")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("SportHub.Api.Models.Facility", b =>
                {
                    b.HasOne("SportHub.Api.Models.Sport", "Sport")
                        .WithMany("Facilities")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("SportHub.Api.Models.Payment", b =>
                {
                    b.HasOne("SportHub.Api.Models.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("SportHub.Api.Models.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("SportHub.Api.Models.Booking", b =>
                {
                    b.Navigation("BookingEquipment");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("SportHub.Api.Models.Equipment", b =>
                {
                    b.Navigation("BookingEquipment");
                });

            modelBuilder.Entity("SportHub.Api.Models.Facility", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("SportHub.Api.Models.Sport", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("SportHub.Api.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
